>P1; sequence of: /var
 
 RCTT                                                        
 TQHTSSMRGVYYPDEIFRSDTLYLTQDLFLPFYSNVTGFHTINHTFDNPVIPFKDGIYFA
 ATEKSNVVRGWVFGSTMNNKSQSVIIINNSTNVVIRACNFELCDNPFFA           
 THTMIFDNAFNCTFEYISDAFS                                      
 FKHLREFVFKNKDGFLYVYKGYQPIDVVRDLPSGFNTLKPIFKLPLGINITNFRAILTAF
 AAYFVGYLKPTTFMLKYDENGTITDAVDCSQNPLAELKCSVKSFEIDKGIYQTSNFRVVP
 SGDVVRFPNITNLCPFGEVFNATKFPSVYAWERKKISNCVADYSVLYNSTFFSTFKCYGV
 SATKLNDLCFSNVYADSFVVKGDDVRQIAPGQTGVIADYNYKLPDDFMGCVLAWNTRNID
 ATSTGNYNYKYRYLRHGKLRPFERDISNVPFSPDGKPCTPPALNCYWPLNDYGFYTTTGI
 GYQPYRVVVLSFELLNAPATVCGPKLSTDLIKNQCVNFNFNGLTGTGVLTPSSKRFQPFQ
 QFGRDVSDFTDSVRDPKTSEILDISPCSFGGVSVITPGTNASSEVAVLYQDVNCTDVSTA
 IHADQLTPAWRIYSTGNNVFQTQAGCLIGAEHVDTSYECDIPIGAGICASYHTV      
 QKSIVAYTMSLGADSSIAYSNNTIAIPTNFSISITTEVMPVSMAKTSVDCNMYICGDSTE
 CANLLLQYGSFCTQLNRALSGIAAEQDRNTREVFAQVKQMYKTPTLKYFGGFNFSQILPD
 PLKPTKRSFIEDLLFNKV                                          
 QYGECL                                                      
 ICAQKFNGLTVLPPLLTDDMIAAYTAALVSGTATAGWTFGAGAALQIPFAMQMAYRFNGI
 GVTQNVLYENQKQIANQFNKAISQIQESLTTTSTALGKLQDVVNQNAQALNTLVKQLSSN
 FGAISSVLNDILSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKM
 SECVLGQSKRVDFCGKGYHLMSFPQAAPHGVVFLHVTYVPSQERNFTTAPAICHEGKAYF
 PREGVFVFNGTSWFITQRNFFSPQIITTDNTFVSGNCDVVIGIINNTVYDPLQPEL    
 RCTT                                                        
 NYTQHTSSMRGVYYPDEIFRSDTLYLTQDLFLPFYSNVTGFHTINHTFDNPVIPFKDGIY
 FAATEKSNVVRGWVFGSTMNNKSQSVIIINNSTNVVIRACNFELCDNPF           
 HTMIFDNAFNCTFEYISDAFS                                       
 FKHLREFVFKNKDGFLYVYKGYQPIDVVRDLPSGFNTLKPIFKLPLGINITNFRAILT  
 AAYFVGYLKPTTFMLKYDENGTITDAVDCSQNPLAELKCSVKSFEIDKGIYQTSNFRVVP
 SGDVVRFPNITNLCPFGEVFNATKFPSVYAWERKKISNCVADYSVLYNSTFFSTFKCYGV
 SATKLNDLCFSNVYADSFVVKGDDVRQIAPGQTGVIADYNYKLPDDFMGCVLAWNTRNID
 ATSTGNYNYKYRYLRHGKLRPFERDISNVPFSPDGKPCTPPALNCYWPLNDYGF      
 QPYRVVVLSFE                                                 
 TVCGPKLSTDLIKNQCVNFNFNGLTGTGVLTPSSKRFQPFQQFGRDVSDFTDSVRDPKTS
 EILDISPCSFGGVSVITPGTNASSEVAVLYQDVNCTDVSTAIHADQLTPAWRIYSTGNNV
 FQTQAGCLIGAEHVDTSYECDIPIGAGICASYHTV                         
 QKSIVAYTMSLGADSSIAYSNNTIAIPTNFSISITTEVMPVSMAKTSVDCNMYICGDSTE
 CANLLLQYGSFCTQLNRALSGIAAEQDRNTREVFAQVKQMYKTPTLKYFGGFNFSQILPD
 PLKPTKRSFIEDLLFNKV                                          
 QYGECL                                                      
 ICAQKFNGLTVLPPLLTDDMIAAYTAALVSGTATAGWTFGAGAALQIPFAMQMAYRFNGI
 GVTQNVLYENQKQIANQFNKAISQIQESLTTTSTALGKLQDVVNQNAQALNTLVKQLSSN
 FGAISSVLNDILSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKM
 SECVLGQSKRVDFCGKGYHLMSFPQAAPHGVVFLHVTYVPSQERNFTTAPAICHEGKAYF
 PREGVFVFNGTSWFITQRNFFSPQIITTDNTFVSGNCDVVIGIINNTVYDPLQPEL    
 RCTT                                                        
 YTQHTSSMRGVYYPDEIFRSDTLYLTQDLFLPFYSNVTGFHTINHTFDNPVIPFKDGIYF
 AATEKSNVVRGWVFGSTMNNKSQSVIIINNSTNVVIRACNFELCDNPF            
 HTMIFDNAFNCTFEYISDAF                                        
 FKHLREFVFKNKDGFLYVYKGYQPIDVVRDLPSGFNTLKPIFKLPLGINITNFRAILTAF
 TSAAAYFVGYLKPTTFMLKYDENGTITDAVDCSQNPLAELKCSVKSFEIDKGIYQTSNFR
 VVPSGDVVRFPNITNLCPFGEVFNATKFPSVYAWERKKISNCVADYSVLYNSTFFSTFKC
 YGVSATKLNDLCFSNVYADSFVVKGDDVRQIAPGQTGVIADYNYKLPDDFMGCVLAWNTR
 NIDATSTGNYNYKYRYLRHGKLRPFERDISNVPFSPDGKPCTPPALNCYWPLNDYGFYTT
 TGIGYQPYRVVVLSFELLNAPATVCGPKLSTDLIKNQCVNFNFNGLTGTGVLTPSSKRFQ
 PFQQFGRDVSDFTDSVRDPKTSEILDISPCSFGGVSVITPGTNASSEVAVLYQDVNCTDV
 STAIHADQLTPAWRIYSTGNNVFQTQAGCLIGAEHVDTSYECDIPIGAGICASYHTV   
 QKSIVAYTMSLGADSSIAYSNNTIAIPTNFSISITTEVMPVSMAKTSVDCNMYICGDSTE
 CANLLLQYGSFCTQLNRALSGIAAEQDRNTREVFAQVKQMYKTPTLKYFGGFNFSQILPD
 PLKPTKRSFIEDLLFNKV                                          
 YGECL                                                       
 ICAQKFNGLTVLPPLLTDDMIAAYTAALVSGTATAGWTFGAGAALQIPFAMQMAYRFNGI
 GVTQNVLYENQKQIANQFNKAISQIQESLTTTSTALGKLQDVVNQNAQALNTLVKQLSSN
 FGAISSVLNDILSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKM
 SECVLGQSKRVDFCGKGYHLMSFPQAAPHGVVFLHVTYVPSQERNFTTAPAICHEGKAYF
 PREGVFVFNGTSWFITQRNFFSPQIITTDNTFVSGNCDVVIGIINNTVYDPLQPEL    
 AQLVESGGALVQPGRSLRLSCAASGFTFRNYAMHWVRQAPATGLQWLAVITSDGRNKFYA
 DSVKGRFTISREDSKNTLYLQMDSLRGEDTAVYYCVTQRDNSRDYFPHYFHDMDVWGQGT
 TVA                                                         
 VLTQSPLSLPVTLGQPASISCRSSQSLVYSDGDTYLNWFQQRPGQSPRRLIYQVSNRDSG
 VPDRFSGSGSGTDFTLKISRVEAEDVGVYYCMQGSHWPPTFGQGTKVEIK          
 AQLVESGGALVQPGRSLRLSCAASGFTFRNYAMHWVRQAPATGLQWLAVITSDGRNKFYA
 DSVKGRFTISREDSKNTLYLQMDSLRGEDTAVYYCVTQRDNSRDYFPHYFHDMDVWGQGT
 TVA                                                         
 AQLVESGGALVQPGRSLRLSCAASGFTFRNYAMHWVRQAPATGLQWLAVITSDGRNKFYA
 DSVKGRFTISREDSKNTLYLQMDSLRGEDTAVYYCVTQRDNSRDYFPHYFHDMDVWGQGT
 TVA                                                         
 VLTQSPLSLPVTLGQPASISCRSSQSLVYSDGDTYLNWFQQRPGQSPRRLIYQVSNRDSG
 VPDRFSGSGSGTDFTLKISRVEAEDVGVYYCMQGSHWPPTFGQGTKVEIK          
 VLTQSPLSLPVTLGQPASISCRSSQSLVYSDGDTYLNWFQQRPGQSPRRLIYQVSNRDSG
 VPDRFSGSGSGTDFTLKISRVEAEDVGVYYCMQGSHWPPTFGQGTKVEIK          
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 Z                                                           
 *                                                           
